version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=3300
      - VITE_API_URL=http://localhost:4001/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    profiles:
      - docker
    command: npm run dev -- --host --port 3300
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4001
      - NODE_ENV=development
    profiles:
      - docker
      - local

networks:
  default:
    name: launchpad-network

volumes:
  node_modules: