version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=3300
      - VITE_API_URL=http://localhost:4001/api
    command: npm run dev -- --host --port 3300
    depends_on:
      - backend
    networks:
      - launchpad-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4001
      - NODE_ENV=development
    networks:
      - launchpad-network

networks:
  launchpad-network:
    driver: bridge